Chore/card edit
HubertKwiatkowski/fischkapp pull request #10
Opened 2023-04-12 18:04 UTC by HubertKwiatkowski

2023-04-12 21:03 UTC, Sumick requested changes
Looks really good! Let's add few improvements, so your logic is more independent. Thing to look at here is to not `querySelector` anything that was not created in the scope of your specific functions. We should parametrize such cases, or create specific element directly in in the same scopes

2023-04-12 21:03 UTC, Sumick commented on js/ui/cardEdit.js
> +  const leftButton = document.querySelector('.btn-left');
**nitpick**: You should try to avoid using hardcoded selectors here. Try to keep all logic encapsulated within this function body. Currently you logic can break if you change these class names - this component won't know about it

2023-04-12 21:03 UTC, Sumick commented on js/ui/cardEdit.js
> +  console.log(params.flashcards[index].front);
**nitpick:** Redundant console.log

2023-04-12 21:03 UTC, Sumick commented on js/ui/cardEditComponent.js
> +  const cardList = document.getElementById('card-list');
**nitpick:** This `card-list` id should be passed as argument, so you can be sure that it won't break if you change it somewhere else

2023-04-12 21:03 UTC, Sumick commented on js/ui/cardList.js
> +    editCardIcon.addEventListener('click', function () {
**nitpick:** I wonder why this logic is a part of list - I mean clicking on edit card button should be a part of one of your card components

2023-04-13 14:55 UTC, NerdbordMentor approved these changes
Overall, the code changes seem to address the task requirements and improve the functionality and user experience of the flashcard app. Here are some specific feedback points:

1. In `getNewCard` function, passing `cardList` as a parameter to `getCardList` function is a good improvement. This will ensure that the updated card list is displayed after adding a new card.

2. Renaming `.card-icon` to `.edit-icon` is a good change as it makes the purpose of the icon clearer.

3. Adding `.edit-value` class for the edit mode input field is a good change as it separates the styles for the edit mode input field from the new card input field.

4. Removing the commented out styles for `.edit-value` and `.card-counter` is a good change as it removes unnecessary clutter from the CSS file.

5. The code changes seem to be well-organized and easy to understand.

Overall, great job on implementing the changes and improving the functionality and user experience of the flashcard app.

2023-04-13 14:56 UTC, merged